Document: snart
Title: Debian snart Manual
Author: <insert document author here>
Abstract: This manual describes what snart is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/snart/snart.sgml.gz

Format: postscript
Files: /usr/share/doc/snart/snart.ps.gz

Format: text
Files: /usr/share/doc/snart/snart.text.gz

Format: HTML
Index: /usr/share/doc/snart/html/index.html
Files: /usr/share/doc/snart/html/*.html
